name = "context-mixer"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "context-mixer-db"
database_id = "6a6f2e3a-f52a-48fd-a644-ed62ffcd7203"

[[r2_buckets]]
binding = "R2"
bucket_name = "context-mixer-files"

[vars]
CLERK_PUBLISHABLE_KEY = "pk_test_d2VsY29tZWQta2l0dGVuLTc0LmNsZXJrLmFjY291bnRzLmRldiQ"
CLERK_FRONTEND_API = "https://welcomed-kitten-74.clerk.accounts.dev"
CLERK_SIGN_IN_URL = "https://welcomed-kitten-74.accounts.dev/sign-in"
# CLERK_SECRET_KEY:
#   local      -> .dev.vars
#   production -> npx wrangler secret put CLERK_SECRET_KEY
